-- MySQL Script generated by MySQL Workbench
-- Di 24 Mai 2022 13:21:08 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Lieferanten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lieferanten` (
  `Handelsregisternummer` INT NOT NULL AUTO_INCREMENT,
  `Firmenname` VARCHAR(45) NULL,
  `Telefonnummer` VARCHAR(45) NULL,
  PRIMARY KEY (`Handelsregisternummer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tablets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tablets` (
  `Inventarnummer` INT NOT NULL AUTO_INCREMENT,
  `Modellbezeichnung` VARCHAR(45) NULL,
  `Kaufdatum` DATE NULL,
  `Lieferanten_Handelsregisternummer` INT NOT NULL,
  PRIMARY KEY (`Inventarnummer`, `Lieferanten_Handelsregisternummer`),
  INDEX `fk_Tablets_Lieferanten1_idx` (`Lieferanten_Handelsregisternummer` ASC),
  CONSTRAINT `fk_Tablets_Lieferanten1`
    FOREIGN KEY (`Lieferanten_Handelsregisternummer`)
    REFERENCES `mydb`.`Lieferanten` (`Handelsregisternummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schueler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schueler` (
  `schuelernr` INT NOT NULL AUTO_INCREMENT,
  `vorname` VARCHAR(45) NULL,
  `nachname` VARCHAR(45) NULL,
  `teilnahme` VARCHAR(45) NULL,
  `Tablets_Inventarnummer` INT NOT NULL,
  PRIMARY KEY (`schuelernr`, `Tablets_Inventarnummer`),
  INDEX `fk_schueler_Tablets1_idx` (`Tablets_Inventarnummer` ASC),
  CONSTRAINT `fk_schueler_Tablets1`
    FOREIGN KEY (`Tablets_Inventarnummer`)
    REFERENCES `mydb`.`Tablets` (`Inventarnummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ags` (
  `agnr` INT NOT NULL AUTO_INCREMENT,
  `agbezeichnung` VARCHAR(45) NULL,
  `raumnr` INT NULL,
  `wochentag` VARCHAR(45) NULL,
  `startzeit` VARCHAR(45) NULL,
  PRIMARY KEY (`agnr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teilnahme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teilnahme` (
  `teilnahmenr` INT NOT NULL AUTO_INCREMENT,
  `ags_agnr` INT NOT NULL,
  `schueler_schuelernr` INT NOT NULL,
  PRIMARY KEY (`teilnahmenr`, `ags_agnr`, `schueler_schuelernr`),
  INDEX `fk_teilnahme_ags1_idx` (`ags_agnr` ASC),
  INDEX `fk_teilnahme_schueler1_idx` (`schueler_schuelernr` ASC),
  CONSTRAINT `fk_teilnahme_ags1`
    FOREIGN KEY (`ags_agnr`)
    REFERENCES `mydb`.`ags` (`agnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teilnahme_schueler1`
    FOREIGN KEY (`schueler_schuelernr`)
    REFERENCES `mydb`.`schueler` (`schuelernr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
